name: Flutter + Node CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter:
    name: Flutter Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/cache_me_if_you_can
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
      - run: flutter config --no-analytics
      - run: flutter pub get

  backend:
    name: Node.js Backend CI
    runs-on: ubuntu-latest
    needs: flutter
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: ./backend
